prSections:
  - title: PRs To Review
    filters: is:open draft:false user-review-requested:@me -review:changes-requested
    type: null
  - title: OTEL PRs
    filters: is:pr is:open repo:open-telemetry/opentelemetry-collector-contrib label:receiver/azureeventhub,receiver/mongodb,receiver/mongodbatlas,receiver/azureblob,receiver/awscloudwatch
    type: null
  - title: My PRs
    filters: is:open author:@me
    type: null
issuesSections:
  - title: OTEL Issues
    filters: is:issue is:open repo:open-telemetry/opentelemetry-collector-contrib label:receiver/azureeventhub,receiver/mongodb,receiver/mongodbatlas,receiver/azureblob,receiver/awscloudwatch
    type: null
defaults:
  preview:
    open: false
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 20
        hidden: true
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
        hidden: true
    issues:
      updatedAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: true
pager:
  diff: ""
confirmQuit: false
smartFilteringAtLaunch: false
