#!/bin/bash

echo "Installing Neovim"
if [ -d "$HOME/git/neovim" ]; then
    echo "Neovim already detected, updating..."
	cd ~/repos/neovim

	git fetch --all --tags --force

	git checkout stable

	echo "Installing"
	make CMAKE_BUILD_TYPE=RelWithDebInfo &>/dev/null
	make distclean
	sudo make install
else
	mkdir ~/git
	cd ~/git
	git clone https://github.com/neovim/neovim
	cd neovim
	git checkout stable
	echo "Installing"
	make CMAKE_BUILD_TYPE=RelWithDebInfo &>/dev/null
	sudo make install
fi
echo "Neovim install complete"
